### PR TITLE
Topic/awelzel/3 serialize unserialize upgrade

### LINKED ISSUE #3: Package does not build with >=zeek-7.1
This package still uses and implements `OpaqueVal::DoSerialize` and `OpaqueVal::DoUnserialize` which were deprecated since 7.0 and are removed with 7.1,

```
[  0%] Built target Zeek_MoreHashes_symlink
[ 11%] Building CXX object CMakeFiles/Zeek_MoreHashes.dir/morehashes.bif.cc.o
[ 22%] Building CXX object CMakeFiles/Zeek_MoreHashes.dir/src/Plugin.cc.o
[ 33%] Building CXX object CMakeFiles/Zeek_MoreHashes.dir/src/MMH3.cc.o
In file included from /Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.cc:1:
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:26:54: error: only virtual member functions can be marked 'override'
   26 |   broker::expected<broker::data> DoSerialize() const override;
      |                                                      ^~~~~~~~
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:28:48: error: only virtual member functions can be marked 'override'
   28 |   bool DoUnserialize(const broker::data &data) override;
      |                                                ^~~~~~~~
In file included from /Users/bbannier/src/packages/zeek/zeek-more-hashes/src/Plugin.cc:3:
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:26:54: error: only virtual member functions can be marked 'override'
   26 |   broker::expected<broker::data> DoSerialize() const override;
      |                                                      ^~~~~~~~
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:28:48: error: only virtual member functions can be marked 'override'
   28 |   bool DoUnserialize(const broker::data &data) override;
      |                                                ^~~~~~~~
In file included from /Users/bbannier/src/packages/zeek/zeek-more-hashes/src/morehashes.bif:2:
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:26:54: error: only virtual member functions can be marked 'override'
   26 |   broker::expected<broker::data> DoSerialize() const override;
      |                                                      ^~~~~~~~
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:28:48: error: only virtual member functions can be marked 'override'
   28 |   bool DoUnserialize(const broker::data &data) override;
      |                                                ^~~~~~~~
2 errors generated.
2 errors generated.
make[2]: *** [CMakeFiles/Zeek_MoreHashes.dir/src/Plugin.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Zeek_MoreHashes.dir/morehashes.bif.cc.o] Error 1
2 errors generated.
make[2]: *** [CMakeFiles/Zeek_MoreHashes.dir/src/MMH3.cc.o] Error 1
make[1]: *** [CMakeFiles/Zeek_MoreHashes.dir/all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by awelzel**
Closes #3

### CODE REVIEW

File: src/MMH3.cc [hunk 1]
```diff
@@ -21,47 +21,40 @@ uint32_t detail::MMH3Val::Result() {
...
+  if (d.Size() != 4 || !d[0].IsBool())
     return false;
 
-  if (!*valid)
-    return true; // while the content is invalid, unserializing was
-                 // successful.
-
-  if (dv.size() < 4)
+  if (!d[1].IsCount() || !d[2].IsCount() || !d[3].IsCount())
     return false;
```
Comment (bbannier) [inline src/MMH3.cc]: Nit: could probably clean up checking for 1) number of values, and 2) value types, e.g.,

```suggestion
  if (d.Size() != 4)
    return false;

  if (!(d[0].IsBool() && d[1].IsCount() && d[2].IsCount() && d[3].IsCount()))
    return false;
```

File: tests/mmh3/bif.zeek [hunk 2]
```diff
@@ -1,27 +1,19 @@
...
-	print msg;
-	exit(1);
-}
-
 event zeek_init() &priority=0 {
 	local h = mmh3_hash_init();
 	mmh3_hash_update(h, "zeek");
 	local r = mmh3_hash_finish(h);
-	my_assert(r == 1898642774, fmt("expected 1898642774 got %s", r));
+	assert r == 1898642774, fmt("expected 1898642774 got %s", r);
```
Comment (bbannier) [inline tests/mmh3/bif.zeek:8]: As an aside, this is IMO a completely reasonable change, but it could break forks enabling ZAM since ZAM unconditionally removes `assert`s so it is completely unusable for testing. Not sure why we do that, and also not really our problem here.

File: .github/workflows/zeek-matrix.yml
Comment (bbannier) [inline .github/workflows/zeek-matrix.yml:1]: Looking at `zeek-nightly.yml` we don't really seem to need the step running `actions/checkout`. Suggest to drop it here as a cleanup, or if we really need it, bump it to `actions/checkout@v4` while at it.

**Review by bbannier — APPROVED** [review]

File: tests/mmh3/bif.zeek (hunk 2 above)
Comment (awelzel) [reply tests/mmh3/bif.zeek:8]: The will know to set `ZEEK_ZAM_KEEP_ASSERTS=1` :-)
