### ISSUE TITLE
Package does not build with >=zeek-7.1

### ISSUE THREAD

**Issue by bbannier** [awelzel/zeek-more-hashes#3]
This package still uses and implements `OpaqueVal::DoSerialize` and `OpaqueVal::DoUnserialize` which were deprecated since 7.0 and are removed with 7.1,

```
[  0%] Built target Zeek_MoreHashes_symlink
[ 11%] Building CXX object CMakeFiles/Zeek_MoreHashes.dir/morehashes.bif.cc.o
[ 22%] Building CXX object CMakeFiles/Zeek_MoreHashes.dir/src/Plugin.cc.o
[ 33%] Building CXX object CMakeFiles/Zeek_MoreHashes.dir/src/MMH3.cc.o
In file included from /Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.cc:1:
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:26:54: error: only virtual member functions can be marked 'override'
   26 |   broker::expected<broker::data> DoSerialize() const override;
      |                                                      ^~~~~~~~
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:28:48: error: only virtual member functions can be marked 'override'
   28 |   bool DoUnserialize(const broker::data &data) override;
      |                                                ^~~~~~~~
In file included from /Users/bbannier/src/packages/zeek/zeek-more-hashes/src/Plugin.cc:3:
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:26:54: error: only virtual member functions can be marked 'override'
   26 |   broker::expected<broker::data> DoSerialize() const override;
      |                                                      ^~~~~~~~
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:28:48: error: only virtual member functions can be marked 'override'
   28 |   bool DoUnserialize(const broker::data &data) override;
      |                                                ^~~~~~~~
In file included from /Users/bbannier/src/packages/zeek/zeek-more-hashes/src/morehashes.bif:2:
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:26:54: error: only virtual member functions can be marked 'override'
   26 |   broker::expected<broker::data> DoSerialize() const override;
      |                                                      ^~~~~~~~
/Users/bbannier/src/packages/zeek/zeek-more-hashes/src/MMH3.h:28:48: error: only virtual member functions can be marked 'override'
   28 |   bool DoUnserialize(const broker::data &data) override;
      |                                                ^~~~~~~~
2 errors generated.
2 errors generated.
make[2]: *** [CMakeFiles/Zeek_MoreHashes.dir/src/Plugin.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Zeek_MoreHashes.dir/morehashes.bif.cc.o] Error 1
2 errors generated.
make[2]: *** [CMakeFiles/Zeek_MoreHashes.dir/src/MMH3.cc.o] Error 1
make[1]: *** [CMakeFiles/Zeek_MoreHashes.dir/all] Error 2
make: *** [all] Error 2
```
